name: Temp pipeline

on:
  push:

jobs:
  action-from-path:
    runs-on: ${{ vars.RUNNER_TAG }}
    steps:
      - name: checking out to repo
        uses: actions/checkout@v4
      - name: SSH setup
        uses: ./.github/actions/sshsetup
        with:
          private_key: ${{ secrets.SSH_KEY }}

  action-from-ref:
    runs-on: ${{ vars.RUNNER_TAG }}
    steps:
      - name: SSH setup
        uses: rkr-projects/ssh-action@V1.0
        with:
          private_key: ${{ secrets.SSH_KEY }}